AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  PHPPhalconTestSAMAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
  PHPPhalconTestSAMFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PHPPhalconTestSAM
      CodeUri: src
      Runtime: provided
      Handler: index.php
      Layers: 
        - （レイヤーARN）
      Events:
        rootAPI:
          Type: Api
          Properties:
            RestApiId: !Ref PHPPhalconTestSAMAPI
            Path: /
            Method: ANY
        proxyAPI:
          Type: Api
          Properties:
            RestApiId: !Ref PHPPhalconTestSAMAPI
            Path: /{proxy+}
            Method: ANY